Lock symbol-observable to 1.0.4.
Next version up is 1.1.0 which causes tsc to fail compilation with
error TS2451: Cannot redeclare block-scoped variable 'Symbol'.

Appears to be related to benlesh/symbol-observable#34